decoder:
  _target_: src.networks.conv64.Decoder
  input_channel: null
  output_channel: null
  ngf: 64
  norm_type: batch
encoder:
  _target_: src.networks.conv64.Encoder
  input_channel: null
  output_channel: null
  ndf: 64
  norm_type: batch