decoder:
  _target_: src.networks.basic.ConvDecoder
  input_channel: null
  output_channel: null
  ngf: 32
  batch_norm: True
encoder:
  _target_: src.networks.basic.ConvEncoder
  input_channel: null
  output_channel: null
  ndf: 32
  batch_norm: True