decoder:
  _target_: src.networks.basic.MLPDecoder
  input_channel: null
  output_channel: null
  width: ${datamodule.width}
  height: ${datamodule.height}
  hidden_dims:
    - 512
    - 512
    - 512
  output_act: tanh
  batch_norm: True
encoder:
  _target_: src.networks.basic.MLPEncoder
  input_channel: null
  output_channel: null
  width: ${datamodule.width}
  height: ${datamodule.height}
  hidden_dims:
    - 512
    - 512
    - 512
  dropout: 0
  output_act: identity
  batch_norm: True