decoder:
  _target_: src.networks.basic.MLPDecoder
  input_channel: null
  output_channel: null
  width: ${datamodule.width}
  height: ${datamodule.height}
  hidden_dims:
    - 1200
    - 1200
    - 1200
    - 4096
  output_act: tanh
  norm_type: batch
encoder:
  _target_: src.networks.basic.MLPEncoder
  input_channel: null
  output_channel: null
  width: ${datamodule.width}
  height: ${datamodule.height}
  hidden_dims:
    - 1200
    - 1200
  dropout: 0
  output_act: identity
  norm_type: batch