decoder:
  _target_: src.networks.basic.MLPDecoder
  input_dim: ${model.latent_dim}
  output_dim: 784
  hidden_dims:
    - 256
    - 512
    - 1024
  output_act: tanh
  batch_norm: True
encoder:
  _target_: src.networks.basic.MLPEncoder
  input_dim: 784
  output_dim: ${model.encoder_dim}
  hidden_dims:
    - 1024
    - 512
    - 256
  dropout: 0
  batch_norm: True