_target_: src.models.aae.AAE
encoder: ${networks.encoder}
decoder: ${networks.decoder}
netD: ${networks.encoder}
loss_mode: vanilla
latent_dim: 128
lrG: 2e-4
lrD: 2e-4
b1: 0.5
b2: 0.999
recon_weight: 1
prior: "normal"