_target_: src.models.age.AGE
encoder: ${networks.encoder}
decoder: ${networks.decoder}
latent_dim: 128
lrE: 2e-4
lrG: 2e-4
b1: 0.5
b2: 0.999
e_recon_z_weight: 0
e_recon_x_weight: 1
g_recon_z_weight: 1
g_recon_x_weight: 0
norm_z: true