_target_: src.models.gan.GAN
loss_mode: vanilla
channels: ${datamodule.channels}
width: ${datamodule.width}
height: ${datamodule.height}
latent_dim: 100
encoder_dim: 1
lrG: 0.0002
lrD: 0.0002
b1: 0.5
b2: 0.999
optim: adam
input_normalize: True
netG: ${networks.decoder}
netD: ${networks.encoder}