_target_: src.models.info_gan.InfoGAN
loss_mode: vanilla
channels: 1
width: 28
height: 28
latent_dim: 110
encoder_dim: 1024
content_dim: 10
lambda_I: 1
lrG: 0.001
lrD: 0.0002
lrQ: 0.0002
b1: 0.5
b2: 0.999
optim: adam
input_normalize: True
netG: ${networks.decoder}
netD: ${networks.encoder}