_target_: src.models.vae.VAE
channels: ${datamodule.channels}
width: ${datamodule.width}
height: ${datamodule.height}
latent_dim: 100
encoder_dim: 200
lr: 0.001
b1: 0.5
b2: 0.999
reg_weight: 1
optim: adam
input_normalize: True
encoder: ${networks.encoder}
decoder: ${networks.decoder}