_target_: src.models.wgan.WGAN
# model parameters
latent_dim: 100
encoder_dim: 1
lrG: 2e-4
lrD: 2e-4
b1: 0
b2: 0.999
optim: rmsprop
netG: ${networks.decoder}
netD: ${networks.encoder}
# special for wgan
n_critic: 5
clip_weight: 0.01