_target_: src.models.wgan.WGAN
# model parameters
latent_dim: 100
lrG: 5e-5
lrD: 5e-5
b1: 0
b2: 0.999
optim: rmsprop
netG: ${networks.decoder}
netD: ${networks.encoder}
# special for wgan
n_critic: 5
clip_weight: 0.01