_target_: src.datamodules.celeba.CelebADataModule
data_dir: ${data_dir}
width: 64
height: 64
channels: 3
batch_size: 128
num_workers: 8
transforms:
  convert: True
  normalize: True
  resize:
    width: ${datamodule.width}
    height: ${datamodule.height}
